components:
    schemas:
        Account:
            # @review
            description:
                An account represents an external account, for example a
                customer business.
            properties:
                description:
                    type: string
                domains:
                    # @review
                    description:
                        The account's email domains. Users assigned to this
                        account generally will have email addresses under one
                        of these domains.
                    items:
                        type: string
                    type: array
                id:
                    format: int64
                    readOnly: true
                    type: integer
                name:
                    type: string
                parentAccountId:
                    format: int64
                    type: integer
                status:
                    type: integer
            type: object
        AccountUser:
            # @review
            description:
                A user that is a member of an account.
            properties:
                emailAddress:
                    format: email
                    type: string
                firstName:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                lastName:
                    type: string
                middleName:
                    type: string
                prefix:
                    type: string
                screenName:
                    type: string
                suffix:
                    type: string
            type: object
info:
    description:
        ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Account"
    version: v1.0
openapi: 3.0.1
paths:
    "/accounts":
        get:
            # @review
            description:
                Retrieves the accounts. Results can be paginated, filtered, searched, and sorted.
            operationId: getAccountsPage
            parameters:
                - in: query
                  name: keywords
                  schema:
                      type: string
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Account"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Account"
                                type: array
                    description:
                        ""
            tags: ["Account"]
        post:
            description:
                Creates a new account
            operationId: postAccount
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Account"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Account"
            responses:
                201:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Account"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Account"
                    # @review
                    description:
                        "Account successfully created"
            tags: ["Account"]
    "/accounts/{accountId}":
        delete:
            # @review
            description:
                Deletes an account.
            operationId: deleteAccount
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                204:
                    content:
                        application/json: {}
                        application/xml: {}
                    description:
                        ""
            tags: ["Account"]
        get:
            description:
                ""
            operationId: getAccount
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Account"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Account"
                    description:
                        ""
            tags: ["Account"]
        patch:
            # @review
            description:
                Updates the account with information sent in the request body. Only the provided fields
                are updated.
            operationId: patchAccount
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Account"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Account"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Account"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Account"
                    # @review
                    description:
                        "Account successfully updated"
        put:
            # @review
            description:
                Replaces the account with information sent in the request body. Any missing fields are deleted
                unless they are required.
            operationId: putAccount
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Account"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/Account"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Account"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/Account"
                    # @review
                    description:
                        "Account successfully replaced"
            tags: ["Account"]
    "/accounts/{accountId}/users":
        get:
            # @review
            description:
                Gets the users assigned to an account
            operationId: getAccountUsersPage
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: query
                  name: filter
                  schema:
                      type: string
                - in: query
                  name: page
                  schema:
                      type: integer
                - in: query
                  name: pageSize
                  schema:
                      type: integer
                - in: query
                  name: search
                  schema:
                      type: string
                - in: query
                  name: sort
                  schema:
                      type: string
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/AccountUser"
                                type: array
                        application/xml:
                            schema:
                                items:
                                    $ref: "#/components/schemas/AccountUser"
                                type: array
                    description:
                        ""
            tags: ["AccountUser"]
        post:
            # @review
            description:
                Creates a user and assigns them to the account
            operationId: postAccountUser
            parameters:
                - in: path
                  name: accountId
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/AccountUser"
                    application/xml:
                        schema:
                            $ref: "#/components/schemas/AccountUser"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/AccountUser"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/AccountUser"
                    description:
                        ""
            tags: ["AccountUser"]